version: "3"
services:
  web:
    build:
      # `context` should be a path to a directory containing a Dockerfile
      context: ./fastapi_app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
#      - caddy_network
      - sim_network
  worker-supply:
    environment:
      - CELERY_TASK_NAME=supply
    build:
      # context should be the name of the folder which define the tasks
      context: task_queue
      dockerfile: Dockerfile_dev
    depends_on:
      - redis
    networks:
      - sim_network
  worker-grid:
    environment:
      - CELERY_TASK_NAME=grid
    build:
      # context should be the name of the folder which define the tasks
      context: task_queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - sim_network
  redis:
    image: redis
    networks:
    - sim_network

networks:
#  caddy_network:
#    external:
#      name: docker_caddy_network
  sim_network:
