FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

COPY . /app
WORKDIR /app

# install requirements
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install gunicorn

# avoid running as root user
RUN useradd --create-home appuser \
    && chown -R appuser /app
USER appuser


# expose the app port
EXPOSE 5001

# run the app server, the last argument match the app variable in the webapp.py file
CMD ["uvicorn", "webapp:app", "--app-dir", "/app/fastapi_app/", "--host", "0.0.0.0", "--port", "5001", "--proxy-headers"]
