version: "3"
services:
  web:
    build:
      args:
        # this should be in a .env file in the root of the repository
        mvs_version: ${MVS_VERSION}
      # `context` should be a path to a directory containing a Dockerfile
      context: ./fastapi_app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
#      - caddy_network
      - eland_network
  worker:
    build:
      args:
        # this should be in a .env file in the root of the repository
        mvs_version: ${MVS_VERSION}
      # context should be the name of the folder which define the tasks
      context: task_queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
    - eland_network
  redis:
    image: redis
    networks:
    - eland_network

networks:
#  caddy_network:
#    external:
#      name: docker_caddy_network
  eland_network:
