apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.name }}-api
  labels:
    app: {{ .Values.project.name }}-api
spec:
  type: ClusterIP
  ports:
    - name: fastapi
      port: {{ .Values.api.port | int }}
      targetPort: {{ .Values.api.port | int }}
      protocol: TCP
  selector:
    app: {{ .Values.project.name }}-api